<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    
    <Title>MoneyExtensions</Title>
    <PackageId>Money.Extension
    
    </PackageId>
    <Description>Extension methods for handling money in .NET applications.</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/Kaikygabriel/Money-Extensions</PackageProjectUrl>
    <PackageTags>money;extensions;finance</PackageTags>
    <Authors>Kaiky Gabriel Alves</Authors>
    <repositoryUrl>https://github.com/Kaikygabriel/Money-Extensions</repositoryUrl>
    <RepositoryType>git</RepositoryType>
    <Version>1.0.1</Version>
    <PackageDescription>Extension methods for handling money in .NET applications.</PackageDescription>
    <icon>https://github.com/Kaikygabriel/Money-Extensions/blob/main/Midia/MoneyExtensions.png</icon>
  </PropertyGroup>
 
</Project>
