name: build and deploy 

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Get Branch Main
        uses: actions/checkout@v7

      - name: Set up .Net
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: '10.0.x'
      
      - name: Build with dotnet
        run: dotnet build -c Release

      - name: Test with dotnet
        run: dotnet test
      
      - name: Create Package
        run: dotnet pack -c Release -o nuget
      
      - name: Publish Package 
        run: dotnet nuget push ./nuget/*.nupkg -k ${{ secrets.KEY_NUGET }} -s https://api.nuget.org/v3/index.json